# -*- coding: utf-8 -*-
"""Untitled23.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UhaUhBllo9hGFOp0C-H2hBflJVtLpis0
"""

#Project Title: "Personal Expense Tracker"
import csv
import os
from datetime import datetime

# Constants
FILE_NAME = "expenses.csv"

#  CSV File
def initialize_file():
    if not os.path.exists(FILE_NAME):
        with open(FILE_NAME, 'w', newline='') as file:
            writer = csv.writer(file)
            writer.writerow(["Date", "Category", "Amount", "Description"])

# Add a new expense
def add_expense(date, category, amount, description):
    with open(FILE_NAME, 'a', newline='') as file:
        writer = csv.writer(file)
        writer.writerow([date, category, amount, description])

# View all expenses
def view_expenses():
    with open(FILE_NAME, 'r') as file:
        reader = csv.reader(file)
        for row in reader:
            print(row)

# Generate expense summary
def summary_report(option):
    expenses = {}
    with open(FILE_NAME, 'r') as file:
        reader = csv.reader(file)
        next(reader)  # Skip header
        for row in reader:
            date, category, amount, _ = row
            amount = float(amount)
            if option == "category":
                expenses[category] = expenses.get(category, 0) + amount
            # Add other options here (e.g., daily, monthly)
    print("Summary Report:", expenses)

# Delete an expense by description
def delete_expense(description):
    rows = []
    with open(FILE_NAME, 'r') as file:
        reader = csv.reader(file)
        for row in reader:
            if description not in row:
                rows.append(row)
    with open(FILE_NAME, 'w', newline='') as file:
        writer = csv.writer(file)
        writer.writerows(rows)

# Menu-driven interface
def main():
    initialize_file()
    while True:
        print("\nExpense Tracker Menu")
        print("1. Add Expense")
        print("2. View Expenses")
        print("3. Generate Summary")
        print("4. Delete Expense")
        print("5. Exit")
        choice = input("Enter your choice: ")

        if choice == "1":
            date = input("Enter date (YYYY-MM-DD): ")
            category = input("Enter category: ")
            amount = input("Enter amount: ")
            description = input("Enter description: ")
            add_expense(date, category, amount, description)
        elif choice == "2":
            view_expenses()
        elif choice == "3":
            option = input("Enter summary option (category/daily/monthly): ")
            summary_report(option)
        elif choice == "4":
            desc = input("Enter description of expense to delete: ")
            delete_expense(desc)
        elif choice == "5":
            print("Exiting...")
            break
        else:
            print("Invalid choice! Please try again.")

if __name__ == "__main__":
    main()